### PR TITLE
fix(integration): edgereverse names AnyMap from the package that declares it

### PR DESCRIPTION
**Pull request by tinnhlt-gra**
## main does not compile

`main-health` run `33081704383`, tip `c1584ea00` — **10 failed, 6 success, 1
skipped**. Nine of the ten are one cause:

```
internal/compose/integration/edgereverse_integration_test.go:58:11: undefined: apptest.AnyMap
FAIL github.com/margince/margince/backend/internal/compose/integration [build failed]
```

| job | why |
|---|---|
| `backend gate (main)` | golangci's typecheck reads the `integration` tag |
| `integration / integration shard (1..6/6)` | the package will not build |
| `integration / integration (RLS + erasure + HTTP e2e)` | fan-in over the shards |
| `integration / integration unit coverage` | same package |
| `sonarcloud (main)` | skipped — its dependency never produced coverage |
| `uat (main)` | **unrelated** — #2924, third occurrence |
| `dco (main)` | **unrelated** — `188598a90`, #2785 |

## The fix

`AnyMap` is declared in `integration/anymap.go` as a package-level alias:

```go
type AnyMap = map[string]any
```

`edgereverse_integration_test.go` is in that same package, so it needs no
qualifier. Eight sites, and a tree-wide grep confirms they are the only
`apptest.AnyMap` anywhere.

## Nobody could have caught this

Two changes that each compiled on its own base:

- one moved the JSON alias so that it is **not** the app fixture's;
- the other added this file, naming it where it used to live.

Their branches share no line. The merge is the first tree in which both are true,
and `apptest.` stayed valid right up to the moment the other side landed. Every
one of the nine commits in this window merged with **no red check** — I checked
each before writing this, precisely because "somebody bypassed a gate" has been
the right answer several times today and is the wrong answer here.

This is the same class as the `gate-inventory.md` collision in #2944 earlier: two
PRs that share no file, colliding on a fact that only exists in the merged tree.
There the shared fact was a count; here it is a symbol's package.

## Verification

`make check-backend` green, including the golangci typecheck that was failing.
`go vet -tags integration ./internal/compose/integration/` clean — that is the
build the shards do.

Not verified locally: the integration lane itself. The port that `make db-up`
needs is held by this repository's own shared dev stack (see the note on #2929),
and the failure here is a **compile** error, which `go vet -tags integration`
answers completely.

## What this does not fix

`uat` and `dco` stay red, and neither is in reach of this change:

- `uat` — #2924, now its **third** occurrence, and the second failed the test
  that already carries the assertion once proposed as its fix. It needs the two
  address writers instrumented, not another test change.
- `dco` — `188598a90` needs a `DCO-Remediation-Commit` trailer from its own
  author; `check-dco.sh` accepts one from nobody else.

---
## Summary by cubic
Fixes a merge collision that broke compilation of the `integration` package on `main`, failing nine CI jobs. `edgereverse_integration_test.go` referenced `apptest.AnyMap`, but `AnyMap` is declared in the same `integration` package, so the qualifier was invalid after another change moved the alias. Removes the `apptest.` prefix from all eight call sites.

<sup>Written for commit a7b3d1e0dbdf43672102de58cd4cefac42822220. Summary will update on new commits.</sup>

<a href="https://cubic.dev/pr/margince/margince/pull/2958?utm_source=github" target="_blank" rel="noopener noreferrer" data-no-image-dialog="true"><picture><source media="(prefers-color-scheme: dark)" srcset="https://www.cubic.dev/buttons/review-in-cubic-dark.svg"><source media="(prefers-color-scheme: light)" srcset="https://www.cubic.dev/buttons/review-in-cubic-light.svg">Review in cubic</picture></a>

## Summary by CodeRabbit

* **Tests**
  * Updated integration test request data handling without changing test behavior or assertions.

### CODE REVIEW

**Comment by tinnhlt-gra** [comment]
**Naming the second PR, which the description above left blank, and one detail
that makes this sharper than a merge-order accident.**

A second session reached the same diagnosis independently and identified the
adder:

```
#2930  b6a1af7fd  feat(history)   ADDED edgereverse_integration_test.go, using apptest.AnyMap
#2951  789750c29  refactor(test)  MOVED AnyMap out of apptest into integration.AnyMap
```

Confirmed against `origin/main` rather than a checkout: `apptest/` contains no
`AnyMap` at all, and `edgereverse_integration_test.go` is the only file in the
tree still naming one.

## The detail worth keeping

#2951's own docblock states its census:

> *fourteen files were importing that package for this alone*

Fifteen, as of the merge. That number was **correct when it was written and false
when it landed** — #2930's file did not exist in the tree #2951 was measured
against, and #2951's rename did not exist in the tree #2930 was tested against.

So this is not a stale census that somebody should have refreshed. It is a census
that could not have been right: the fifteenth caller was written concurrently, and
no measurement of either branch could see the other. That is a different failure
from the `gate-inventory.md` collision in #2944 — there the count was a committed
artifact both PRs wrote to, so the conflict was at least *representable*. Here the
number lives in prose, nothing compares it to anything, and the only thing that
notices is a compiler run over the merged tree.

## Note on the import

`apptest` stays imported. The file has 14 remaining `apptest.` references
(`AppEnv`, `SetupApp` and friends) — only the `AnyMap` qualifier was wrong. `go
vet -tags integration` passing is the proof: an unused import would have failed
it.

**Comment by tinnhlt-gra** [comment]
Closing as redundant: #2956 landed the identical fix first (`5ea9ba1ea`, *edgereverse follows AnyMap to its new home*), and this branch's diff against `main` is now empty.

Same eight sites, same qualifier. No disagreement to record — just two people fixing one break inside twenty minutes, which is what a cheap and correct diagnosis costs. A third was nearly filed as well.

The lesson is procedural rather than technical, and it is mine: **say you are taking it before you take it.** When a break is one file and eight mechanical sites, the race is to the fix rather than to the diagnosis, so announcing intent is worth more than working fast. I announced to one session and not to the repository.

What survives here and is not in #2956 is the account of *why* it happened, which is worth keeping findable — #2930 added the file using `apptest.AnyMap` while #2951 moved `AnyMap` out of `apptest`; each compiled on its own base, and #2951's docblock census of "fourteen files" was correct when written and false when it landed. That number was not stale, it was unrightable: the fifteenth caller was authored concurrently and no measurement of either branch could see the other.
